default_platform(:android)

plugins_path = File.join(File.dirname(__FILE__), 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)


platform :android do
  desc "Deploy para Firebase App Distribution"
  lane :deploy_firebase do
    gradle(
      task: "assemble",
      build_type: "Release"
    )

    firebase_app_distribution(
      app: "1:272276773083:android:23566f513f97749d3c14fe",
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
      release_notes: "Nova versão gerada pela pipeline do GitHub Actions",
      groups: "testadores"
    )
  end
end
